### ISSUE TITLE
Run tests made for GetRss, SetRss and RssTest

### ISSUE THREAD

**Issue by cristina-sirbu** [h2opaulh2o/IP-A3-Project#36]
Run the tests made for GetRss, SetRss and RssTest and document the result. (The classes that are tested, short description of how it is implemented and whether or not the tests passed. If it didn't passed the test please add some opinions about what do you think is wrong.) The documentation will be sent to me (sirbucristina.is@gmail.com)

**Comment by axenianita** [comment]
done
